export const FAKE_POPULARS = [
  {
    adult: false,
    backdrop_path: "/butPVWgcbtAjL9Z7jU7Xj1KA8KD.jpg",
    genre_ids: [10767, 35],
    id: 22980,
    origin_country: ["US"],
    original_language: "en",
    original_name: "Watch What Happens Live with Andy Cohen",
    overview:
      "Bravo network executive Andy Cohen discusses pop culture topics with celebrities and reality show personalities.",
    popularity: 3789.948,
    poster_path: "/onSD9UXfJwrMXWhq7UY7hGF2S1h.jpg",
    first_air_date: "2009-07-16",
    name: "Watch What Happens Live with Andy Cohen",
    vote_average: 3.01,
    vote_count: 38,
  },
];

export const FAKE_RECOMMENDATION = [
  {
    adult: false,
    backdrop_path: "/q79U95wgkocoECitZPfRDhZXBNz.jpg",
    id: 14814,
    name: "Keeping Up with the Kardashians",
    original_language: "en",
    original_name: "Keeping Up with the Kardashians",
    overview:
      "A peek inside the exploits and privileged private lives of the blended Kardashian-Jenner family, including sisters Kim, Kourtney and Khloé.",
    poster_path: "/nddXOC8wYpIDv7giLzjjqIg8WDA.jpg",
    media_type: "tv",
    genre_ids: [10764],
    popularity: 310.531,
    first_air_date: "2007-10-14",
    vote_average: 7.479,
    vote_count: 862,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/xl1wGwaPZInJo1JAnpKqnFozWBE.jpg",
    id: 59941,
    name: "The Tonight Show Starring Jimmy Fallon",
    original_language: "en",
    original_name: "The Tonight Show Starring Jimmy Fallon",
    overview:
      "After Jay Leno's second retirement from the program, Jimmy Fallon stepped in as his permanent replacement. After 42 years in Los Angeles the program was brought back to New York.",
    poster_path: "/g4amxJvtpnY79J77xeamnAEUO8r.jpg",
    media_type: "tv",
    genre_ids: [35, 10767],
    popularity: 1619.973,
    first_air_date: "2014-02-17",
    vote_average: 5.867,
    vote_count: 297,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/y1NtXk3YzmXOIqEBtwjojONPjqT.jpg",
    id: 69320,
    name: "Trial & Error",
    original_language: "en",
    original_name: "Trial & Error",
    overview:
      "A bright-eyed New York lawyer takes his first big case defending an eccentric poetry professor accused of murdering his wife.",
    poster_path: "/8o9taPRFH6TXCFDhjO3zKHiN034.jpg",
    media_type: "tv",
    genre_ids: [35],
    popularity: 32.864,
    first_air_date: "2017-03-14",
    vote_average: 7.5,
    vote_count: 43,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: null,
    id: 4107,
    name: "The Steve Harvey Show",
    original_language: "en",
    original_name: "The Steve Harvey Show",
    overview:
      "Down on his luck and out of money, former R&B star Steve Hightower lands a music teacher gig at an inner-city Chicago school.  Showing who's in charge with his unorthodox approach, Steve discovers a new groove at Washington High School.",
    poster_path: "/iGUWv21kgKc79bpYxImk2nTIPin.jpg",
    media_type: "tv",
    genre_ids: [35, 18],
    popularity: 95.806,
    first_air_date: "1996-08-25",
    vote_average: 7.2,
    vote_count: 18,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg",
    id: 76479,
    name: "The Boys",
    original_language: "en",
    original_name: "The Boys",
    overview:
      "A group of vigilantes known informally as “The Boys” set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.",
    poster_path: "/7Ns6tO3aYjppI5bFhyYZurOYGBT.jpg",
    media_type: "tv",
    genre_ids: [10765, 10759],
    popularity: 331.691,
    first_air_date: "2019-07-25",
    vote_average: 8.471,
    vote_count: 9238,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/4wwWDjLfJVMt2hh8DIa2rzEx5VS.jpg",
    id: 62425,
    name: "Dark Matter",
    original_language: "en",
    original_name: "Dark Matter",
    overview:
      "The six-person crew of a derelict spaceship awakens from stasis in the farthest reaches of space. Their memories wiped clean, they have no recollection of who they are or how they got on board. The only clue to their identities is a cargo bay full of weaponry and a destination: a remote mining colony that is about to become a war zone. With no idea whose side they are on, they face a deadly decision. Will these amnesiacs turn their backs on history, or will their pasts catch up with them?",
    poster_path: "/oWYOFBvIMkW64n51uD4mdje6k2u.jpg",
    media_type: "tv",
    genre_ids: [10765, 18],
    popularity: 97.882,
    first_air_date: "2015-06-12",
    vote_average: 6.676,
    vote_count: 728,
    origin_country: ["CA"],
  },
  {
    adult: false,
    backdrop_path: "/yGNnjoIGOdQy3douq60tULY8teK.jpg",
    id: 63247,
    name: "Westworld",
    original_language: "en",
    original_name: "Westworld",
    overview:
      "A dark odyssey about the dawn of artificial consciousness and the evolution of sin. Set at the intersection of the near future and the reimagined past, it explores a world in which every human appetite, no matter how noble or depraved, can be indulged.",
    poster_path: "/8MfgyFHf7XEboZJPZXCIDqqiz6e.jpg",
    media_type: "tv",
    genre_ids: [10765, 37],
    popularity: 283.331,
    first_air_date: "2016-10-02",
    vote_average: 8.059,
    vote_count: 5188,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/pxeqQX4qFQ0cVxPt5SWZENV5BH3.jpg",
    id: 456,
    name: "The Simpsons",
    original_language: "en",
    original_name: "The Simpsons",
    overview:
      "Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.",
    poster_path: "/vHqeLzYl3dEAutojCO26g0LIkom.jpg",
    media_type: "tv",
    genre_ids: [10751, 16, 35],
    popularity: 1305.689,
    first_air_date: "1989-12-17",
    vote_average: 8.009,
    vote_count: 9475,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/20eIP9o5ebArmu2HxJutaBjhLf4.jpg",
    id: 87108,
    name: "Chernobyl",
    original_language: "en",
    original_name: "Chernobyl",
    overview:
      "The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.",
    poster_path: "/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 152.19,
    first_air_date: "2019-05-06",
    vote_average: 8.662,
    vote_count: 5783,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/rIe3PnM6S7IBUmvNwDkBMX0i9EZ.jpg",
    id: 1399,
    name: "Game of Thrones",
    original_language: "en",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    media_type: "tv",
    genre_ids: [10765, 18, 10759],
    popularity: 839.328,
    first_air_date: "2011-04-17",
    vote_average: 8.446,
    vote_count: 22789,
    origin_country: ["US"],
  },
];
